title: Jetson Containers Tutorial
description: A comprehensive tutorial for Jetson Containers
baseurl: "/jetson-containers-tutorial"
url: "https://chitoku.github.io"

# Build settings
markdown: kramdown
theme: just-the-docs
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-mermaid

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Collections
collections:
  tutorials:
    output: true
    permalink: /:collection/:name

# Just the Docs settings
just_the_docs:
  # Main navigation
  nav_external_links:
    - title: GitHub Repository
      url: https://github.com/dusty-nv/jetson-containers

  # Aux links for the upper right navigation
  aux_links:
    "View on GitHub":
      - "//github.com/chitoku/jetson-containers-tutorial"

  # Color scheme
  color_scheme: light

  # Search
  search: true
  search_tokenizer_separator: /[\s\-/]+/

  # Mermaid
  mermaid:
    version: "9.4.3"
    theme: "default"
    config:
      startOnLoad: true
      themeVariables:
        primaryColor: "#ff0000"
        primaryTextColor: "#fff"
        primaryBorderColor: "#7C0000"
        lineColor: "#F8B229"
        secondaryColor: "#006100"
        tertiaryColor: "#fff"