remote_theme: just-the-docs/just-the-docs
title: "Jetson Containers Tutorial"
description: "A comprehensive guide to working with Jetson Containers"
baseurl: "/jetson-containers-tutorial"
url: "https://chitoku.github.io"

# Enable or disable the site search
search_enabled: true

# Enable or disable heading anchors
heading_anchors: true

# Aux links for the upper right navigation
aux_links:
  "GitHub Repository":
    - "//github.com/dusty-nv/jetson-containers"

# Makes Aux links open in a new tab
aux_links_new_tab: false

# Sort order for navigation links
nav_order: 1

# Footer content
footer_content: "Copyright &copy; 2024 NVIDIA. Distributed under the MIT License."

# Color scheme currently only supports "dark" or nil (default)
color_scheme: nil

# Google Analytics Tracking (optional)
# google_analytics_ua: UA-XXXXXXXXX-X

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Collections
collections:
  tutorials:
    output: true
    permalink: /:collection/:name

# Just the Docs settings
just_the_docs:
  # Main navigation
  nav_external_links:
    - title: GitHub Repository
      url: https://github.com/dusty-nv/jetson-containers

  # Color scheme
  color_scheme: light

  # Search
  search: true
  search_tokenizer_separator: /[\s\-/]+/

  # Mermaid
  mermaid:
    version: "9.4.3"
    theme: "default"
    config:
      startOnLoad: true
      themeVariables:
        primaryColor: "#ff0000"
        primaryTextColor: "#fff"
        primaryBorderColor: "#7C0000"
        lineColor: "#F8B229"
        secondaryColor: "#006100"
        tertiaryColor: "#fff"